### ISSUE TITLE
提几个意见喔

### ISSUE THREAD

**Issue by anglesgirl** [lala437/FREEKAN_ACVS#7]
比如说优酷的视频自动优先调用接口1  
爱奇艺调用接口2 这样的功能
因为某些接口会只能解析某个视频

设置视频列表排序 可以自己把 爱奇艺排在第一个 腾讯第二个 这样的功能

还有就是 资源站的同名视频播放链接 可以整合到自动同步360影视的播放列表里 并且为第一个播放  比如说 羞羞的铁拳这个片子 爱奇艺有 资源站也有 我在资源站添加这个片以后 在爱奇艺的播放列表前面先显示资源站的也先播放资源站的   因为解析很容易失效 资源站不容易失效

所以很希望能够使用资源站替代解析来稳定播放

**Comment by anglesgirl** [comment]
你的程序能够识别付费视频跟免费视频
解析的适合 可以分开解析更好
免费的随便找一个无广告解析都很方便
经常失效的都是付费视频 所以希望分别处理一下

**Comment by lala437** [comment]
意见已收到,谢谢

**Comment by anglesgirl** [comment]
留言板功能使用畅言需要备案才能用
建议多加几个其他的
国外不是有api可以用吗 国外服务器无影响
